# tools/legal_agents/nda_generator.py
import os
import datetime

def generate_nda(party_b_name: str, brand_name: str = "ctrl Startup Studio") -> str:
    """Compiles a standard Mutual Non-Disclosure Agreement (NDA)."""
    target_dir = "./generated_assets/research_reports/legal"
    os.makedirs(target_dir, exist_ok=True)
    
    date_today = datetime.date.today().strftime("%B %d, %Y")
    
    nda_text = f"""MUTUAL NON-DISCLOSURE AGREEMENT
    
Effective Date: {date_today}
Party A: {brand_name} ("Disclosing Party")
Party B: {party_b_name} ("Receiving Party")

1. DEFINITION OF CONFIDENTIAL INFORMATION
"Confidential Information" means any proprietary information, technical data, trade secrets, software architecture, hardware schematics, or know-how.

2. OBLIGATIONS OF RECEIVING PARTY
The Receiving Party shall hold and maintain the Confidential Information in strictest confidence for the sole and exclusive benefit of the Disclosing Party. 

3. TIME PERIODS
The nondisclosure provisions of this Agreement shall survive the termination of this Agreement and Receiving Party's duty to hold Confidential Information in confidence shall remain in effect until the Confidential Information no longer qualifies as a trade secret.

[Auto-Generated by the ctrl Matrix]
"""
    file_path = os.path.join(target_dir, f"NDA_{party_b_name.replace(' ', '_')}.txt")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(nda_text)
        
    return f"📝 **NDA Compiled:** Document saved to `{file_path}`"
