# tools/crypto_agents/smart_contract_gen.py
import os

def generate_erc20_contract(token_name: str, token_symbol: str, initial_supply: int = 1000000) -> str:
    """Scaffolds a standard ERC-20 Solidity smart contract."""
    target_dir = "./generated_assets/web_builds/contracts"
    os.makedirs(target_dir, exist_ok=True)
    
    solidity_code = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title {token_name}
 * Auto-generated by the ctrl matrix.
 */
contract {token_symbol}Token is ERC20, Ownable {{
    constructor() ERC20("{token_name}", "{token_symbol}") Ownable(msg.sender) {{
        _mint(msg.sender, {initial_supply} * 10 ** decimals());
    }}
}}
"""
    file_path = os.path.join(target_dir, f"{token_symbol}Token.sol")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(solidity_code)
        
    return f"📜 **Smart Contract Compiled:** Solidity code written to `{file_path}`"
