# tools/dev_agents/android_kotlin_gen.py
import os

def generate_kotlin_activity(activity_name: str, package_name: str = "com.ctrl.app") -> str:
    """Scaffolds a standard Android Kotlin Activity with lifecycle methods."""
    target_dir = "./generated_assets/app_apks/kotlin_src"
    os.makedirs(target_dir, exist_ok=True)
    
    kotlin_code = f"""package {package_name}

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import android.util.Log

/**
 * Auto-generated by the ctrl matrix.
 * Lead Architect: Advait
 */
class {activity_name}Activity : AppCompatActivity() {{

    private val TAG = "ctrl_{activity_name}"

    override fun onCreate(savedInstanceState: Bundle?) {{
        super.onCreate(savedInstanceState)
        // setContentView(R.layout.activity_{activity_name.lower()})
        
        Log.d(TAG, "Matrix Activity Initialized")
    }}
}}
"""
    file_path = os.path.join(target_dir, f"{activity_name}Activity.kt")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(kotlin_code)
        
    return f"🤖 **Kotlin Activity Compiled:** Code written to `{file_path}`"
